import { Metadata } from 'next'
import SEOForService from '../../../components/SEOForService'

interface PageProps {
  params: Promise<{ service: string }>
}

// Generate static params for all SEO-for service pages
export async function generateStaticParams() {
  const services = [
    'travel-services', 'hotel-services', 'fintech-services', 'appliance-repair-services',
    'locksmith-services', 'cbd-services', 'grand-rapids-services', 'wedding-photographers-services',
    'cosmetics-services', 'home-services', 'professional-firm-services', 'spanish-services',
    'virtual-assistant-services', 'architects-services', 'electricians-services', 'security-guard-services',
    'translation-services', 'french-services', 'chiropractor-services', 'concierge-services',
    'crypto-services', 'german-services', '3d-printing-services', 'abortion-clinic',
    'abrasives-supplier', 'academic-department', 'adult-entertainment-club', 'adult-entertainment-store',
    'adult-foster-care-service', 'adventure-sports', 'advertising-agency', 'aerial-photographer',
    'aero-dance-class', 'aerobics-instructor', 'aerospace-company', 'african-goods-store',
    'aged-care', 'agistment-service', 'agricultural-association', 'agricultural-cooperative',
    'agricultural-machinery-manufacturer', 'agricultural-organization', 'agricultural-production',
    'agricultural-service', 'agrochemicals-supplier', 'aikido-school', 'air-compressor-supplier',
    'air-conditioning-contractor', 'air-conditioning-store', 'air-conditioning-system-supplier',
    'air-duct-cleaning-service', 'air-filter-supplier', 'air-force-base', 'air-taxi',
    'aircraft-maintenance-company', 'aircraft-rental-service', 'aircraft-supply-store',
    'airline-ticket-agency', 'airplane', 'airport', 'airport-shuttle-service',
    'alcohol-manufacturer', 'alcohol-retail-monopoly', 'alcoholic-beverage-wholesaler',
    'aluminum-frames-supplier', 'aluminum-supplier', 'aluminum-welder', 'aluminum-window',
    'american-football-field', 'amusement-center', 'amusement-park', 'anesthesiologist',
    'anganwadi-center', 'animal-feed-store', 'animal-hospital', 'animal-rescue-service',
    'antique-furniture-store', 'apartment-building', 'apartment-rental-agency', 'apostolic-church',
    'appliance-rental-service', 'appliance-repair-service', 'appliance-store',
    'appliances-customer-service', 'appraiser', 'apprenticeship-center', 'aquaculture-farm',
    'aquatic-centre', 'arboretum', 'arborist-&-tree-surgeon', 'archaeological-museum',
    'archery-club', 'archery-range', 'archery-store', 'architects-association',
    'architectural-designer', 'architectural-salvage-store', 'architecture-firm',
    'architecture-school', 'archive', 'arena', 'armed-forces-association', 'armenian-church',
    'army-barracks', 'army-&-navy-surplus-shop', 'army-facility', 'army-museum',
    'aromatherapy-class', 'aromatherapy-service', 'aromatherapy-supply-store', 'art-cafe',
    'art-center', 'art-dealer', 'art-gallery', 'art-museum', 'art-restoration-service',
    'art-school', 'art-studio', 'art-supply-store', 'artificial-plant-supplier', 'artist',
    'arts-organization', 'asbestos-testing-service', 'ashram', 'asian-grocery-store',
    'asian-household-goods-store', 'asphalt-contractor', 'asphalt-mixing-plant',
    'assemblies-of-god-church', 'assistante-maternelle', 'assisted-living-facility',
    'association-or-organization', 'aston-martin-dealer', 'astrologer', 'athletic-club',
    'athletic-field', 'athletic-park', 'athletic-track', 'atm', 'attorney-referral-service',
    'atv-dealer', 'atv-rental-service', 'atv-repair-shop', 'auction-house',
    'audio-visual-equipment-supplier', 'audio-visual-equipment-repair-service', 'audiologist',
    'audiovisual-equipment-rental-service', 'auditorium', 'auto-air-conditioning-service',
    'auto-body-parts-supplier', 'auto-body-shop', 'auto-broker', 'auto-electrical-service',
    'auto-glass-repair-service', 'auto-glass-shop', 'auto-insurance-agency',
    'auto-parts-manufacturer', 'auto-parts-market', 'auto-parts-store', 'auto-repair-shop',
    'auto-restoration-service', 'auto-spring-shop', 'auto-tag-agency', 'auto-tune-up-service',
    'auto-window-tinting-service', 'automation-company', 'automobile-storage-facility',
    'aviation-consultant', 'baby-store', 'bag-shop', 'bagel-shop', 'bail-bonds-service',
    'bait-shop', 'bakery', 'bakery-equipment', 'baking-supply-store', 'ballet-school',
    'balloon-ride-tour-agency', 'ballroom-dance-instructor', 'bangle-shop', 'bank',
    'bankruptcy-attorney', 'bankruptcy-service', 'banquet-hall', 'baptist-church',
    'bar-stool-supplier', 'bar-tabac', 'barbecue-area', 'barber-shop', 'barber-supply-store',
    'bariatric-surgeon', 'barrel-supplier', 'barrister', 'baseball-club', 'baseball-field',
    'bathroom-remodeler', 'batik-clothing-store', 'battery-manufacturer', 'battery-wholesaler',
    'batting-cage-center', 'bbq-area', 'beach-cleaning-service', 'beach-entertainment-shop',
    'beach-volleyball-club', 'beauty-product-supplier', 'beauty-products-wholesaler',
    'beauty-salon', 'beauty-school', 'beauty-supply-store', 'bed-&-breakfast', 'bed-shop',
    'bedding-store', 'bedroom-furniture-store', 'bee-relocation-service', 'beer-distributor',
    'beer-garden', 'beer-hall', 'beer-store', 'belt-shop', 'betting-agency',
    'beverage-distributor', 'bicycle-club', 'biotechnology-company', 'biotechnology-engineer',
    'bird-control-service', 'bird-shop', 'birth-center', 'blast-cleaning-service',
    'blinds-shop', 'blood-bank', 'blood-donation-center', 'blueprint-service',
    'board-game-club', 'boarding-school', 'boat-dealer', 'boat-ramp', 'body-shaping-class',
    'boiler-manufacturer', 'boiler-supplier', 'bonsai-plant-supplier', 'book-publisher',
    'book-store', 'bookkeeping-service', 'bookmaker', 'books-wholesaler', 'boot-camp',
    'border-crossing-station', 'botanical-garden', 'bowling-alley', 'bowling-club',
    'bowling-supply-shop', 'boys-high-school', 'bpo-company', 'bpo-placement-agency',
    'brake-shop', 'brazilian-pastelaria', 'brewery', 'brewing-supply-store', 'brewpub',
    'brick-manufacturer', 'bridal-shop', 'bridge', 'bridge-club', 'building-designer',
    'building-restoration-service', 'building-society', 'bus-and-coach-company', 'bus-company',
    'bus-charter', 'bus-depot', 'bus-ticket-agency', 'bus-tour-agency',
    'business-administration-service', 'business-attorney', 'business-banking-service',
    'business-broker', 'business-center', 'business-park', 'business-school', 'cabinet-maker',
    'cabinet-store', 'call-center', 'call-shop', 'camera-repair-shop', 'camera-store',
    'camper-shell-supplier', 'campground', 'camping-cabin', 'camping-farm', 'camping-store',
    'cancer-treatment-center', 'candle-store', 'candy-store', 'cane-furniture-store',
    'cannery', 'castle', 'car-accessories-store', 'car-alarm-supplier', 'car-battery-store',
    'car-dealer', 'car-detailing-service', 'car-factory', 'car-finance-&-loan-company',
    'car-inspection-station', 'car-leasing-service', 'car-manufacturer', 'car-racing-track',
    'car-rental-agency', 'car-repair-&-maintenance-service', 'car-security-system-installer',
    'car-sharing-location', 'car-stereo-store', 'car-wash', 'carpenter',
    'carpet-cleaning-service', 'carpet-installer', 'carpet-manufacturer', 'carpet-store',
    'caterer', 'catering-food-&-drink-supplier', 'cathedral', 'catholic-cathedral',
    'catholic-church', 'catholic-school', 'cbse-school', 'cd-store', 'ceiling-supplier',
    'cell-phone-accessory-store', 'cell-phone-charging-station', 'cell-phone-store',
    'central-bank', 'chapel', 'chartered-accountant', 'chartered-surveyor',
    'chemical-engineering-service', 'chemical-exporter', 'chemical-manufacturer',
    'chemical-plant', 'chemical-wholesaler', 'chemistry-lab', 'chess-&-card-club',
    'chess-club', 'chess-instructor', 'childrens-camp', 'childrens-clothing-store',
    'childrens-farm', 'childrens-cafe', 'childrens-club', 'childrens-library',
    'childrens-theater', 'chimney-services', 'chocolate-shop', 'chimney-sweep',
    'chinaware-store', 'chinese-language-instructor', 'chinese-language-school',
    'chinese-medicine-clinic', 'chinese-medicine-store', 'chinese-supermarket',
    'chinese-takeaway', 'chinese-tea-house', 'chocolate-artisan', 'chocolate-cafe',
    'chocolate-factory', 'cricket-club', 'cricket-ground', 'cricket-shop', 'crypto-atm',
    'cultural-association', 'cultural-center', 'cultural-landmark', 'curling-club',
    'curling-hall', 'custom-confiscated-goods-store', 'custom-home-builder',
    'custom-label-printer', 'custom-t-shirt-store', 'custom-tailor', 'customs-broker',
    'customs-consultant', 'customs-department', 'customs-office', 'customs-warehouse',
    'cycle-rickshaw-stand', 'cycling-park', 'dairy-farm-equipment-supplier', 'dairy-store',
    'dairy-supplier', 'dance-club', 'dance-company', 'dance-conservatory', 'dance-hall',
    'dance-pavillion', 'dance-school', 'dance-store', 'dart-supply-store',
    'data-entry-service', 'data-recovery-service', 'dating-service', 'day-care-center',
    'day-spa', 'deaf-church', 'deaf-service', 'debris-removal-service', 'debt-collecting',
    'debt-collection-agency', 'deli', 'delivery-service', 'dental-clinic', 'dental-hygienist',
    'dental-implants-provider', 'dental-insurance-agency', 'dental-laboratory',
    'dental-radiology', 'dental-school', 'dental-supply-store', 'dentist',
    'denture-care-center', 'department-for-regional-development', 'department-of-education',
    'department-of-finance', 'department-of-housing', 'department-of-social-services',
    'department-of-state-treasure', 'department-of-transportation', 'department-store',
    'dept-of-city-treasure', 'dermatologist', 'desalination-plant', 'design-agency',
    'design-engineer', 'design-institute', 'dessert-shop', 'detention-center', 'dhaba',
    'diabetes-equipment-supplier', 'diamond-dealer', 'diesel-engine-dealer',
    'diesel-engine-repair-service', 'diesel-fuel-supplier', 'dietitian', 'digital-printer',
    'digital-printing-service', 'diner', 'dinner-theater', 'distance-learning-center',
    'distribution-service', 'district-attorney', 'district-council',
    'district-government-office', 'district-office', 'dive-club', 'dive-shop',
    'diving-contractor', 'divorce-lawyer', 'divorce-service', 'dj-supply store',
    'do-it-yourself-shop', 'dock-builder', 'doctor', 'dodge-dealer', 'dog-breeder',
    'dog-day-care-center', 'dog-park', 'dog-trainer', 'dog-walker', 'dollar-store',
    'domestic-abuse-treatment-center', 'domestic-airport', 'door-manufacturer', 'door-shop',
    'door-supplier', 'door-warehouse', 'doula', 'drafting-equipment-supplier',
    'drafting-service', 'drama-school', 'drama-theater', 'drawing-lessons', 'dress-store',
    'dressmaker', 'dried-flower-shop', 'drilling-contractor', 'drilling-equipment-supplier',
    'drivers-license-training-school', 'driving-school', 'driving-test-center', 'drug-store',
    'drug-testing-service', 'dry-cleaner', 'dryer-vent-cleaning-service', 'dump-truck-dealer',
    'dvd-store', 'dye-store', 'e-commerce-agency', 'e-commerce-service',
    'ear-piercing-service', 'earth-works-company', 'eastern-orthodox-church', 'ecological-park',
    'ecologists-association', 'economic-consultant', 'economic-development-agency',
    'education-center', 'educational-consultant', 'educational-institution',
    'educational-supply-store', 'educational-testing-service', 'elder-law-attorney',
    'electric-bicycle-store', 'electric-generator-shop', 'electric-motor-repair-shop',
    'electric-motor-scooter-dealer', 'electric-motor-vehicle-dealer', 'electric-motorcycle-dealer',
    'electric-utility-company', 'electric-vehicle-charging-station',
    'electric-vehicle-charging-station-contractor', 'electrical-engineer',
    'electrical-equipment-manufacturer', 'electrical-equipment-supplier',
    'electrical-installation-service', 'electrical-products-wholesaler', 'electrical-repair-shop',
    'electrical-supply-store', 'electrician', 'electronic-engineering-service',
    'electronic-parts-supplier', 'electronics-accessories-wholesaler', 'electronics-exporter',
    'electronics-hire-shop', 'electronics-manufacturer', 'electronics-store',
    'electronics-vending-machine', 'electronics-wholesaler', 'elementary-school',
    'elevator-manufacturer', 'elevator-service', 'emergency-care-physician',
    'emergency-care-service', 'emergency-dental-service', 'emergency-locksmith-service',
    'emergency-management-ministry', 'emergency-room', 'emergency-training',
    'emergency-training-school', 'emergency-veterinarian-service', 'employment-agency',
    'employment-attorney', 'employment-center', 'endodontist', 'endoscopist',
    'energy-equipment-&-solutions', 'engine-rebuilding-service', 'engineer',
    'engineering-consultant', 'engineering-school', 'english-language-camp',
    'english-language-instructor', 'english-language-school', 'entertainer',
    'entertainment-agency', 'envelope-supplier', 'environment-office',
    'environment-renewable-natural-resources', 'environmental-consultant',
    'environmental-engineer', 'environmental-organization', 'episcopal-church',
    'equestrian-club', 'equestrian-facility', 'equestrian-store', 'equipment-exporter',
    'equipment-importer', 'equipment-rental-agency', 'equipment-supplier', 'erotic-massage',
    'escape-room-center', 'escrow-service', 'espresso-bar', 'estate-appraiser',
    'estate-liquidator', 'estate-litigation-attorney', 'estate-planning-attorney',
    'ethnographic-museum', 'evangelical-church', 'evening-school', 'event-management-company',
    'event-planner', 'event-technology-service', 'event-venue', 'excavating-contractor',
    'executive-search-firm', 'executive-suite-rental-agency', 'executor',
    'exercise-equipment-store', 'exhibit', 'exhibition-&-trade-centre', 'exhibition-planner',
    'exporter', 'extended-stay-hotel', 'eye-care-center', 'eyebrow-bar', 'eyelash-salon',
    'fabric-product-manufacturer', 'fabric-wholesaler', 'fabrication-engineer', 'facial-spa',
    'factory-equipment-supplier', 'faculty-of-arts', 'faculty-of-chemistry',
    'faculty-of-geography-&-history', 'faculty-of-law', 'faculty-of-pharmacy',
    'faculty-of-psychology', 'faculty-of-science', 'faculty-of-sports', 'fairground',
    'family-counselor', 'family-day-care-service', 'family-law-attorney',
    'family-planning-center', 'family-planning-counselor', 'family-practice-physician',
    'family-service-center', 'farm', 'farm-bureau', 'farm-equipment-repair-service',
    'farm-equipment-supplier', 'farm-household-tour', 'farm-shop', 'farmers-market',
    'farmstay', 'fashion-accessories-store', 'fashion-design-school', 'fashion-designer',
    'favela', 'fax-service', 'federal-agency-for-technical-relief', 'federal-credit-union',
    'federal-government-office', 'federal-police', 'federal-reserve-bank', 'felt-boots-store',
    'fence-contractor', 'fence-supply-store', 'fencing-salon', 'fencing-school',
    'feng-shui-shop', 'ferris-wheel', 'ferry-service', 'fertility-clinic',
    'fertility-physician', 'festival', 'fiberglass-repair-service', 'fiberglass-supplier',
    'figurine-shop', 'filipino-grocery-store', 'film-production-company', 'filtration-plant',
    'finance-broker', 'financial', 'financial-audit', 'financial-consultant',
    'financial-institution', 'financial-planner', 'fingerprinting-service',
    'finishing-materials-supplier', 'fire-damage-restoration-service',
    'fire-department-equipment-supplier', 'fire-protection-consultant',
    'fire-protection-equipment-supplier', 'fire-protection-service',
    'fire-protection-system-supplier', 'fire-station', 'firearms-academy',
    'fireplace-manufacturer', 'fireplace-store', 'firewood-supplier', 'fish-spa', 'fish-store',
    'fishing-camp', 'fishing-charter', 'fishing-club', 'fishing-store', 'fitness-center',
    'fitness-equipment-wholesaler', 'fitted-furniture-supplier', 'flight-school',
    'floor-refinishing-service', 'floor-sanding-&-polishing-service', 'flooring-contractor',
    'flooring-store', 'florist', 'flower-delivery', 'flower-designer', 'flower-market',
    'fmcg-goods-wholesaler', 'fmcg-manufacturer', 'food-&-beverage-consultant',
    'food-&-beverage-exporter', 'food-bank', 'food-broker', 'food-court',
    'food-manufacturing-supply', 'food-manufacturer', 'food-processing-company',
    'food-producer', 'food-products-supplier', 'food-seasoning-manufacturer', 'foot-bath',
    'foot-care', 'foot-massage-parlor', 'foreign-consulate',
    'foreign-exchange-students-organization', 'foreign-languages-program-school',
    'forensic-consultant', 'forestry-service', 'forklift-rental-service', 'formal-wear-store',
    'fortress', 'fortune-telling-services', 'fraternal-organization', 'free-clinic',
    'free-parking-lot', 'freight-forwarding-service', 'french-language-school',
    'fresh-food-market', 'friends-church', 'frituur', 'frozen-dessert-supplier',
    'frozen-food-manufacturer', 'frozen-food-store', 'frozen-yogurt-shop',
    'fruit-&-vegetable-store', 'full-dress-rental-service', 'full-gospel-church',
    'funeral-director', 'funeral-home', 'fur-coat-shop', 'fur-manufacturer', 'fur-service',
    'furnace-parts-supplier', 'furnace-repair-service', 'furnace-store',
    'furniture-accessories', 'furniture-accessories-supplier', 'furniture-maker',
    'furniture-manufacturer', 'furniture-rental-service', 'furniture-repair-shop',
    'furniture-store', 'futon-store', 'gamblin-house', 'game-store', 'garage-builder',
    'garage-door-supplier', 'garbage-collection-service', 'garbage-dump',
    'garbage-dump-service', 'garden', 'garden-building-supplier', 'garden-center',
    'garden-furniture-shop', 'garden-machinery-supplier', 'gardener', 'garment-exporter',
    'gas-company', 'gas-cylinders-supplier', 'gas-engineer', 'gas-logs-supplier',
    'gas-station', 'gasfitter', 'gastroenterologist', 'gay-&-lesbian-organization',
    'gay-bar', 'gay-night-club', 'gay-sauna', 'gazebo-builder', 'gemologist', 'genealogist',
    'general-contractor', 'general-education-school', 'general-hospital',
    'general-practice-attorney', 'general-practitioner', 'general-store',
    'geological-research-company', 'geotechnical-engineer', 'german-language-school',
    'gift-basket-store', 'gift-shop', 'gift-wrap-store', 'girl-bar', 'glass-blower',
    'glass-merchant', 'glass-repair-service', 'glass-shop', 'glasses-repair-service',
    'glassware-wholesaler', 'glazier', 'gmc-dealer', 'go-kart-track', 'gold-deller',
    'gold-mining-company', 'goldfish-store', 'goldsmith', 'golf-cart-dealer', 'golf-club',
    'golf-course', 'golf-course-builder', 'golf-driving-range', 'golf-instructor',
    'golf-shop', 'gospel-church', 'government-college', 'government-hospital',
    'government-school', 'gps-supplier', 'graduate-school', 'graffiti-removal-service',
    'grain-elevator', 'grammar-school', 'green-energy-supplier', 'greengrocer', 'greenhouse',
    'greeting-card-shop', 'greyhound-stadium', 'grill', 'grill-store',
    'grocery-delivery-service', 'grocery-store', 'ground-self-defense-force', 'group-home',
    'grow-shop', 'guardia-civil', 'guest-house', 'guitar-instructor', 'guitar-store',
    'gun-club', 'gun-shop', 'gurudwara', 'gutter-cleaning-service', 'gym',
    'gymnasium-school', 'gymnastics-center', 'gymnastics-club', 'gynecologist',
    'hair-extensions-supplier', 'hair-removal-service', 'hair-replacement-service',
    'hair-salon', 'hair-transplantation-clinic', 'hairdresser', 'ham-shop', 'hand-surgeon',
    'handbags-shop', 'handball-club', 'handicapped-transportation-service', 'handicraft',
    'handicraft-exporter', 'handicraft-museum', 'handicraft-school', 'handicrafts-wholesaler',
    'hardware-store', 'hat-shop', 'haunted-house', 'hawaiian-goods-store', 'hawker-center',
    'hawker-stall', 'hay-supplier', 'head-start-center', 'health-&-beauty-shop',
    'health-consultant', 'health-counselor', 'health-food-store', 'health-insurance-agency',
    'health-resort', 'hearing-aid-repair-service', 'hearing-assistance-earphone-store',
    'heart-hospital', 'heating-contractor', 'heating-equipment-supplier',
    'helicopter-tour-agency', 'heliport', 'helium-gas-supplier', 'helpline', 'hematologist',
    'hepatologist', 'herb-shop', 'herbalist', 'heritage-museum', 'heritage-preservation',
    'high-school', 'higher-secondary-school', 'highway-patrol', 'hiking-guide',
    'hip-hop-dance-class', 'hispanic-church', 'historical-landmark', 'historical-place-museum',
    'historical-society', 'history-museum', 'hobby-store', 'hockey-club', 'hockey-rink',
    'hockey-supply-store', 'holding-company', 'holiday-apartment', 'holiday-apartment-rental',
    'holiday-home', 'home-audio-store', 'home-builder', 'home-goods-store', 'home-hairdresser',
    'home-health-care-service', 'home-help', 'home-help-service-agency',
    'home-improvement-store', 'home-inspector', 'home-insurance-agency', 'home-theater-store',
    'homekill-service', 'honey-farm', 'horse-breeder', 'horse-rental-service',
    'horse-riding-school', 'horse-transport-supplier', 'horseback-riding-service',
    'horseshoe-smith', 'hose-supplier', 'hospice', 'hospital-department',
    'hospital-equipment-&-supplies', 'hospitality-&-tourism-school', 'hospitality-high-school',
    'host-club', 'hot-tub-repair-service', 'hot-tub-store', 'hot-water-system-supplier',
    'hotel', 'hotel-management-school', 'hotel-supply-store', 'house-cleaning-service',
    'house-clearance-service', 'household-chemicals-supplier', 'household-goods-wholesaler',
    'housing-authority', 'housing-complex', 'housing-cooperative', 'housing-development',
    'housing-society', 'human-resource-consulting', 'hunting-&-fishing-store', 'hunting-area',
    'hunting-club', 'hunting-store', 'hvac-contractor', 'hydroponics-equipment-supplier',
    'hyperbaric-medicine-physician', 'hypnotherapy-service', 'ice-cream-shop',
    'ice-skating-club', 'ice-skating-rink', 'ice-supplier',
    'immigration-&-naturalization-service', 'immigration-attorney', 'immigration-detention-centre',
    'immunologist', 'impermeabilization-service', 'incineration-plant',
    'income-protection-insurance-agency', 'income-tax-help-association', 'indian-takeaway',
    'indoor-cycling', 'indoor-golf-course', 'indoor-swimming-pool',
    'industrial-chemicals-wholesaler', 'industrial-consultant', 'industrial-design-company',
    'industrial-engineer', 'industrial-engineers-association', 'industrial-equipment-supplier',
    'industrial-framework-supplier', 'industrial-real-estate-agency', 'industrial-supermarket',
    'industrial-technical-engineers-association', 'industrial-vacuum-equipment-supplier',
    'infectious-disease-physician', 'infiniti-dealer', 'information-services', 'inn',
    'insolvency-service', 'institute-of-geography-&-statistics', 'institute-of-technology',
    'instrumentation-engineer','bar','alcohol'
  ]

  return services.map((service) => ({
    service: service,
  }))
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { service } = await params
  const serviceName = service.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
  
  return {
    title: `${serviceName} SEO Services - Boost Your Industry Visibility`,
    description: `Drive organic growth in the ${serviceName.toLowerCase()} industry with our expert SEO services. Boost rankings, increase leads, and maximize ROI. Contact us today.`,
    alternates: {
      canonical: `https://www.nspglobalservices.com/seo-for/${service}`,
    },
  }
}

export default async function SEOForServicePage({ params }: PageProps) {
  const { service } = await params
  
  return <SEOForService service={service} />
}